In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("houses_properties_data.csv", low_memory = False)

In [3]:
df.columns.tolist()

['listingProvider',
 'buildingPermits',
 'propertyTaxRate',
 'contact_recipients',
 'longitude',
 'countyFIPS',
 'cityId',
 'timeOnZillow',
 'url',
 'zestimate',
 'imgSrc',
 'zpid',
 'zipcode',
 'livingAreaValue',
 'zestimateLowPercent',
 'isListedByOwner',
 'propertyTypeDimension',
 'streetAddress',
 'county',
 'taxHistory',
 'stateId',
 'countyId',
 'timeZone',
 'homeType',
 'livingAreaUnits',
 'comingSoonOnMarketDate',
 'livingArea',
 'bathrooms',
 'annualHomeownersInsurance',
 'state',
 'rentZestimate',
 'building',
 'brokerId',
 'yearBuilt',
 'brokerageName',
 'dateSold',
 'price',
 'pageViewCount',
 'description',
 'homeStatus',
 'homeFacts',
 'latitude',
 'datePosted',
 'bedrooms',
 'nearbyHomes',
 'monthlyHoaFee',
 'priceHistory',
 'favoriteCount',
 'schools',
 'zestimateHighPercent',
 'mlsid',
 'city',
 'providerListingID',
 'country',
 'currency',
 'contingentListingType',
 'solarPotential.sunScore',
 'solarPotential.solarFactor',
 'solarPotential.buildFactor',
 'solarPotenti

In [4]:
##Let's look at all columns
columns_unique = df.columns.tolist()

In [5]:
##If the columns have only one element for all rows it's pretty useless
##If one column has more than 8950 nan values, we should ditch that column too
df.listingProvider.nunique()

0

In [6]:
df[columns_unique]

listingProvider  buildingPermits  propertyTaxRate  \
0                 NaN              NaN             1.47   
1                 NaN              NaN             1.47   
2                 NaN              NaN             1.47   
3                 NaN              NaN             1.47   
4                 NaN              NaN             1.47   
...               ...              ...              ...   
9154              NaN              NaN             1.86   
9155              NaN              NaN             1.86   
9156              NaN              NaN             1.86   
9157              NaN              NaN             1.86   
9158              NaN              NaN             1.86   

                                     contact_recipients  longitude  \
0     [{'agent_reason': 1, 'zpro': None, 'recent_sal... -97.750490   
1     [{'agent_reason': 1, 'zpro': None, 'recent_sal... -97.488280   
2     [{'agent_reason': 1, 'zpro': None, 'recent_sal... -97.649800   
3     [{'agent_reason': 1, 'zpro': None, 'recent_sal... -97.437614   
4     [{'agent_reason': 1, 'zpro': None, 'recent_sal... -97.752600   
...                                                 ...        ...   
9154  [{'agent_reason': 1, 'zpro': None, 'recent_sal... -96.945750   
9155  [{'agent_reason': 1, 'zpro': None, 'recent_sal... -96.793860   
9156  [{'agent_reason': 1, 'zpro': None, 'recent_sal... -96.769210   
9157  [{'agent_reason': 1, 'zpro': None, 'recent_sal... -96.929634   
9158  [{'agent_reason': 1, 'zpro': None, 'recent_sal... -96.657440   

      countyFIPS   cityId timeOnZillow  \
0        48497.0  23820.0       3 days   
1        48497.0  36648.0      52 days   
2        48497.0   3772.0     130 days   
3        48497.0      NaN        1 day   
4        48497.0  23820.0       3 days   
...          ...      ...          ...   
9154     48139.0   7797.0      61 days   
9155     48139.0   7797.0      43 days   
9156         NaN   7797.0     305 days   
9157     48139.0  36121.0     141 days   
9158     48139.0  42291.0     411 days   

                                                    url  zestimate  ...  \
0     /homedetails/2104-16th-St-Bridgeport-TX-76426/...        NaN  ...   
1     /homedetails/509-Pettit-Dr-Newark-TX-76071/220...   157200.0  ...   
2     /homedetails/813-E-Highway-114-Boyd-TX-76023/2...        NaN  ...   
3     /homedetails/105-Dodge-City-Ct-Newark-TX-76071...   275600.0  ...   
4     /homedetails/1412-Hovey-St-Bridgeport-TX-76426...   227900.0  ...   
...                                                 ...        ...  ...   
9154  /homedetails/4218-Fm-66-Waxahachie-TX-75167/67...  1350000.0  ...   
9155  /homedetails/971-Bells-Chapel-Rd-Waxahachie-TX...        NaN  ...   
9156  /homedetails/145-Hartsfield-Dr-Waxahachie-TX-7...        NaN  ...   
9157  /homedetails/1765-N-Mockingbird-Ln-Midlothian-...        NaN  ...   
9158  /homedetails/1100-Estate-Dr-Ennis-TX-75119/125...        NaN  ...   

     listingProvider.sourceText  listingProvider.title  \
0                           NaN                    NaN   
1                           NaN                    NaN   
2                           NaN                    NaN   
3                           NaN                    NaN   
4                           NaN                    NaN   
...                         ...                    ...   
9154                        NaN                    NaN   
9155                        NaN                    NaN   
9156                        NaN                    NaN   
9157                        NaN                    NaN   
9158                        NaN                    NaN   

      listingProvider.postingWebsiteURL  listingProvider.agentLicenseNumber  \
0                                   NaN                                 NaN   
1                                   NaN                                 NaN   
2                                   NaN                                 NaN   
3                                   N

In [7]:
len(df)

9159

In [8]:
##If there are basically no data within a specific columns, we should just remove it

def drop_useless_columns(dataframe):
    columns_unique = dataframe.columns.tolist()
    columns_to_drop = list()
    rows_check = (dataframe.shape[0]) * 0.90
    for i in range(len(columns_unique)):
        column = columns_unique[i]
        if (dataframe.loc[dataframe[column].isnull()].shape[0] >= rows_check) or (df[column].nunique() <= 1):
            columns_to_drop.append(column)
    columns_chosen = list(set(columns_unique) - set(columns_to_drop))
    #print("Drop these columns: ", columns_to_drop)
    return dataframe[columns_chosen]

In [9]:
df2 = drop_useless_columns(df)

In [10]:
df['taxHistory'][0]

"[{'time': 1622819614662, 'valueIncreaseRate': 0.33283103, 'taxIncreaseRate': 0.3328346, 'taxPaid': 2814.6, 'value': 132670}, {'time': 1591283614662, 'valueIncreaseRate': 0.097101286, 'taxIncreaseRate': 0.0095227705, 'taxPaid': 2111.74, 'value': 99540}, {'time': 1559661214662, 'valueIncreaseRate': 0.02138917, 'taxIncreaseRate': 0.02137655, 'taxPaid': 2091.82, 'value': 90730}, {'time': 1528125214662, 'valueIncreaseRate': 0.05398671, 'taxIncreaseRate': 0.048089422, 'taxPaid': 2048.04, 'value': 88830}, {'time': 1496589214662, 'valueIncreaseRate': 0.113195084, 'taxIncreaseRate': 0, 'taxPaid': 1954.07, 'value': 84280}, {'time': 1465053214662, 'valueIncreaseRate': 0.014743332, 'taxIncreaseRate': 0, 'taxPaid': None, 'value': 75710}, {'time': 1433430814662, 'valueIncreaseRate': -0.009820836, 'taxIncreaseRate': 0, 'taxPaid': None, 'value': 74610}, {'time': 1401894814662, 'valueIncreaseRate': -0.009725325, 'taxIncreaseRate': 0, 'taxPaid': None, 'value': 75350}, {'time': 1370358814662, 'valueIncr

In [11]:
##Remember we have a list of counties run through a loop 
##The order of that list can determine the number that represents the counties
##'wise county, tx', 'denton county, tx', 'collin county, tx', 'parker county, tx', 'tarrant county, tx', 
##'dallas county, tx', 'rockwall county, tx', 'kaufman county, tx', 'johnson county, tx', 'ellis county, tx'
##Follow the order of the county above, these numbers represents these counties respectively.
df2['countyId'].unique()

array([ 333,  988,  951, 1308, 2049,  978, 2516, 1833, 1827,  498])

In [12]:
all_columns = df2.columns.tolist()
all_columns

['resoFacts.hasSpa',
 'resoFacts.livingArea',
 'resoFacts.onMarketDate',
 'timeOnZillow',
 'resoFacts.sewer',
 'resoFacts.coveredSpaces',
 'resoFacts.parcelNumber',
 'monthlyHoaFee',
 'resoFacts.associationFeeIncludes',
 'mortgageRates.thirtyYearFixedRate',
 'resoFacts.foundationDetails',
 'datePosted',
 'resoFacts.isNewConstruction',
 'resoFacts.communityFeatures',
 'zestimateHighPercent',
 'zpid',
 'resoFacts.parkingFeatures',
 'resoFacts.hasCooling',
 'resoFacts.fireplaces',
 'resoFacts.hasAttachedGarage',
 'streetAddress',
 'resoFacts.buyerAgencyCompensation',
 'resoFacts.patioAndPorchFeatures',
 'listed_by.rating_average',
 'resoFacts.carportSpaces',
 'contact_recipients',
 'resoFacts.virtualTour',
 'resoFacts.pricePerSquareFoot',
 'address.city',
 'schools',
 'resoFacts.hasCarport',
 'annualHomeownersInsurance',
 'resoFacts.levels',
 'listed_by.business_name',
 'homeStatus',
 'resoFacts.atAGlanceFacts',
 'resoFacts.hasGarage',
 'mortgageRates.fifteenYearFixedRate',
 'resoFacts.ve

In [13]:
len(all_columns)

145

In [14]:
df2['listed_by.phone.areacode'].unique()

array([940., 972., 817.,  nan, 480., 214., 888., 833., 469., 713., 877.,
       682., 210., 979., 925., 248., 844., 862., 512., 806., 281., 919.,
       903., 510., 208., 443., 630., 323., 504., 732., 818., 347., 936.,
       832., 949., 774., 717., 405., 760., 805., 702., 707., 847., 314.,
       845., 952., 916., 515., 305., 615., 346., 678., 773., 855., 714.,
       650., 385., 927., 201., 938., 432., 254., 646., 407., 206., 917.,
       310., 408., 956., 909., 361., 918., 516., 980., 915., 263., 720.,
       325., 706., 808., 843., 970., 864., 505., 801., 251., 804., 757.,
       520., 330., 612., 985., 404., 571., 303., 866., 863., 313., 216.,
       419., 620., 247., 830., 913., 937., 928., 409., 870., 302., 704.,
       858., 951., 603., 424., 929., 316., 740., 973., 770., 813., 318.,
       812., 601., 425., 561.])

In [15]:
df2['livingAreaValue']

0       1072.0
1       1316.0
2       2849.0
3       1330.0
4       1492.0
         ...  
9154    2826.0
9155    3360.0
9156    1680.0
9157    3640.0
9158    5165.0
Name: livingAreaValue, Length: 9159, dtype: float64

In [16]:
df2['schools']

0       [{'link': 'https://www.greatschools.org/school...
1       [{'link': 'https://www.greatschools.org/school...
2       [{'link': 'https://www.greatschools.org/school...
3       [{'link': 'https://www.greatschools.org/school...
4       [{'link': 'https://www.greatschools.org/school...
                              ...                        
9154    [{'link': 'https://www.greatschools.org/school...
9155    [{'link': 'https://www.greatschools.org/school...
9156    [{'link': 'https://www.greatschools.org/school...
9157    [{'link': 'https://www.greatschools.org/school...
9158    [{'link': 'https://www.greatschools.org/school...
Name: schools, Length: 9159, dtype: object

In [17]:
df2['resoFacts.waterSource'].unique()

array(["['City Water']", "['Well']",
       "['City Water', 'Individual Water Meter']", "['Co-op Water']", nan,
       "['Co-op Water', 'Individual Water Meter']", "['Private', 'Well']",
       "['City Water', 'Individual Water Meter', 'Well']",
       "['City Water', 'Co-op Water', 'Individual Water Meter']",
       "['MUD Water']", "['Co-op Water', 'MUD Water']", "['Private']",
       "['Individual Water Meter']", "['City Water', 'MUD Water']",
       "['City Water', 'Individual Water Meter', 'MUD Water']",
       "['City Water', 'Individual Water Meter', 'Rural Water District']",
       "['Co-op Water', 'Individual Water Meter', 'Well']",
       "['Co-op Water', 'Well']", "['City Water', 'Well']",
       "['City Water', 'Rural Water District']",
       "['Individual Water Meter', 'MUD Water']",
       "['City Water', 'Co-op Water']",
       "['City Water', 'Master Water Meter']",
       "['Individual Water Meter', 'Rural Water District']",
       "['Individual Water Meter', 'Private

In [18]:
df2['resoFacts.exteriorFeatures'].unique()

array([nan, "['Kennel', 'Storage']", "['Covered Patio/Porch']", ...,
       "['Attached Grill', 'Covered Patio/Porch', 'Rain Gutters', 'RV/Boat Parking']",
       "['Covered Patio/Porch', 'Fire Pit', 'Rain Gutters', 'Lighting', 'Outdoor Living Center', 'RV Hookup', 'RV/Boat Parking', 'Sport Court', 'Storage']",
       "['Balcony', 'Covered Patio/Porch', 'Fire Pit', 'RV/Boat Parking', 'Stable/Barn']"],
      dtype=object)

In [19]:
df2['listed_by.rating_average']

0       5.0
1       5.0
2       5.0
3       0.0
4       NaN
       ... 
9154    0.0
9155    0.0
9156    4.9
9157    NaN
9158    0.0
Name: listed_by.rating_average, Length: 9159, dtype: float64

In [20]:
df2['resoFacts.greenEnergyEfficient'].unique()

array([nan, "['Construction', 'Insulation']",
       "['Appliances', 'Doors', 'HVAC', 'Insulation', 'Thermostat', 'Windows']",
       "['HVAC', 'Low Flow Commode']",
       "['Solar Electric System', 'Windows']", "['Water Heater']",
       "['Drought Tolerant Plants']",
       "['Insulation', 'Thermostat', 'Windows']",
       "['12 inch+ Attic Insulation', 'Appliances', 'HVAC', 'Thermostat', 'Windows']",
       "['Appliances', 'Doors', 'HVAC', 'Insulation', 'Rain / Freeze Sensors', 'Thermostat', 'Windows']",
       "['Appliances', 'Doors', 'HVAC', 'Insulation', 'Rain / Freeze Sensors', 'Thermostat', 'Water Heater', 'Windows']",
       "['Appliances', 'HVAC', 'Thermostat', 'Windows']",
       "['12 inch+ Attic Insulation', 'HVAC', 'Insulation', 'Lighting', 'Rain / Freeze Sensors', 'Thermostat', 'Windows']",
       "['Appliances', 'HVAC', 'Insulation', 'Windows']", "['HVAC']",
       "['Appliances']", "['Low Flow Commode']", "['Windows']",
       "['Appliances', 'Drought Tolerant Plants'

In [21]:
##nan here is actually a float number
##Replaces null values with ['None'] or sth
##Create columns based on lists within a row's variable
##Columns that have this: 'resoFacts.patioAndPorchFeatures', 'resoFacts.waterSource', 'resoFacts.exteriorFeatures'
##'resoFacts.vegetation', 'resoFacts.greenEnergyEfficient', 'resoFacts.foundationDetails', 'resoFacts.utilities'
##'resoFacts.appliances', 'resoFacts.flooring', 'resoFacts.parkingFeatures', 'resoFacts.fireplaceFeatures'
##'resoFacts.laundryFeatures', 'resoFacts.propertySubType', 'resoFacts.laundryFeatures', 'resoFacts.securityFeatures',
##'schools', 'resoFacts.associationFeeIncludes', 'resoFacts.cooling', 'resoFacts.fireplaces', 'resoFacts.windowFeatures'
##'resoFacts.heating', 'resoFacts.sewer', 'resoFacts.poolFeatures' 

##utilities that is null can be seen as electricity
##For green energy, we can create a column where if it has green energy or not
df2['resoFacts.utilities'].unique()

array(["['Electricity Connected']", nan, "['Overhead Utilities']", ...,
       "['Electricity Connected', 'Gravel/Rock', 'Outside City Limits', 'Propane']",
       "['All Weather Road', 'Co-op Electric', 'Outside City Limits', 'No City Services']",
       "['All Weather Road', 'Co-op Electric', 'Gravel/Rock', 'Sewer Available']"],
      dtype=object)

In [22]:
df2.loc[df2['resoFacts.greenEnergyEfficient'].isnull()][['streetAddress']]

streetAddress
0              2104 16th St
1             509 Pettit Dr
2         813 E Highway 114
3         105 Dodge City Ct
4             1412 Hovey St
...                     ...
9150    1901 Oak St #B066BC
9152             3511 Fm 66
9153          102 Old Pecan
9155    971 Bells Chapel Rd
9157  1765 N Mockingbird Ln

[6590 rows x 1 columns]

In [23]:
df2['resoFacts.greenEnergyEfficient'].isnull().sum()

6590

In [24]:
##Some has HOA fee, some don't so we have to add a column that shows if the property have hoa or not
df2.loc[~(df2['monthlyHoaFee'].isnull()) | ~(df2['resoFacts.hoaFee'].isnull())][['monthlyHoaFee', 'resoFacts.hoaFee']]

monthlyHoaFee resoFacts.hoaFee
3              37.0   $110 quarterly
15             25.0    $300 annually
28             37.0    $440 annually
32             43.0   $130 quarterly
35             37.0   $110 quarterly
...             ...              ...
9132           31.0    $375 annually
9135          115.0  $1,375 annually
9138          163.0  $1,950 annually
9150           29.0    $350 annually
9158           27.0    $325 annually

[4968 rows x 2 columns]

In [25]:
##Fill null sun score values with mean or median of sun scores in the zip code area
np.sort(df2.loc[~(df2['solarPotential.sunScore'].isnull())]['solarPotential.sunScore'].unique())

array([22.14, 22.18, 22.19, 22.21, 22.23, 22.51, 22.57, 22.59, 22.6 ,
       22.61, 22.62, 22.63, 22.64, 22.65, 22.66, 22.67, 22.68, 22.69,
       22.7 , 22.71, 22.72, 22.74, 36.22, 37.83, 37.9 , 38.63, 39.44,
       40.3 , 41.02, 41.06, 42.62, 42.63, 43.42, 43.5 , 44.24, 44.26,
       45.83, 45.84, 45.89, 45.9 , 46.09, 47.44, 48.22, 49.02, 49.03,
       49.04, 49.06, 49.13, 49.83, 49.9 , 49.92, 50.71, 51.44, 51.5 ,
       52.22, 52.23, 52.28, 53.09, 53.1 , 53.82, 53.83, 53.84, 53.9 ,
       54.18, 54.26, 54.6 , 54.62, 54.63, 54.69, 54.7 , 55.01, 55.38,
       55.4 , 55.42, 55.43, 55.48, 55.5 , 55.51, 55.78, 56.22, 56.23,
       56.24, 56.28, 56.29, 57.01, 57.02, 57.03, 57.05, 57.07, 57.09,
       57.1 , 57.14, 57.38, 57.82, 57.83, 57.91, 58.09, 58.26, 58.27,
       58.58, 58.62, 58.63, 58.66, 58.7 , 58.72, 58.98, 59.4 , 59.42,
       59.43, 59.44, 59.49, 59.55, 60.23, 60.24, 60.26, 60.28, 60.33,
       61.02, 61.03, 61.06, 61.1 , 61.13, 61.14, 61.36, 61.43, 61.46,
       61.71, 61.78,

In [26]:
df2['resoFacts.homeType'].unique()

array(['SingleFamily', 'Other', 'Unknown', 'Townhouse'], dtype=object)

In [27]:
df2['propertyTypeDimension'].unique()

array(['Single Family', 'Home Type Unknown', 'Townhouse'], dtype=object)

In [28]:
df2['resoFacts.interiorFeatures'].unique()

array(["['Eat-in Kitchen']", "['Cable TV Available']", nan, ...,
       "['Decorative Lighting', 'Granite Counters', 'Kitchen Island', 'Open Floorplan', 'Vaulted Ceiling(s)', 'Walk-In Closet(s)']",
       "['Cable TV Available', 'Central Vacuum', 'Decorative Lighting', 'Sound System Wiring']",
       "['Cable TV Available', 'High Speed Internet Available', 'Smart Home System', 'Wet Bar']"],
      dtype=object)

In [29]:
df2['resoFacts.communityFeatures'].unique()

array([nan, "['Lake']",
       "['Boat Ramp', 'Clubhouse', 'Community Pool', 'Golf', 'Jogging Path/Bike Path', 'Marina', 'Park', 'Playground']",
       ..., "['Fishing', 'Gated']",
       "['Electric Car Charging Station', 'Fishing', 'Gated', 'Golf', 'Guarded Entrance', 'Jogging Path/Bike Path', 'Lake', 'Marina', 'Park', 'Perimeter Fencing', 'Playground', 'Sidewalks', 'Tennis Court(s)', 'Other']",
       "['Community Pool', 'Pool', 'Sauna']"], dtype=object)

In [30]:
df2['taxHistory']

0       [{'time': 1622819614662, 'valueIncreaseRate': ...
1       [{'time': 1622819616122, 'valueIncreaseRate': ...
2       [{'time': 1622819617536, 'valueIncreaseRate': ...
3       [{'time': 1622819619115, 'valueIncreaseRate': ...
4       [{'time': 1622820309665, 'valueIncreaseRate': ...
                              ...                        
9154    [{'time': 1622832223440, 'valueIncreaseRate': ...
9155    [{'time': 1622832224713, 'valueIncreaseRate': ...
9156                                                  NaN
9157    [{'time': 1622832227306, 'valueIncreaseRate': ...
9158    [{'time': 1622832228527, 'valueIncreaseRate': ...
Name: taxHistory, Length: 9159, dtype: object

In [31]:
df2['resoFacts.parcelNumber']

0       A0018900702
1       R1970050200
2       A0457010402
3       R0294B09200
4       B1891001000
           ...     
9154         190300
9155         201664
9156         180945
9157         187223
9158         235705
Name: resoFacts.parcelNumber, Length: 9159, dtype: object

In [32]:
##The annual amount is currently this year
df2['resoFacts.taxAnnualAmount']

0       2749.0
1       2089.0
2       6006.0
3       3313.0
4       2318.0
         ...  
9154       NaN
9155    8789.0
9156    3699.0
9157    7249.0
9158     945.0
Name: resoFacts.taxAnnualAmount, Length: 9159, dtype: float64

In [33]:
##resoFacts.hasAssociation is if the house has HOA or not
df2['resoFacts.elementarySchoolDistrict']

0       Bridgeport ISD
1        Northwest ISD
2             Boyd ISD
3        Northwest ISD
4       Bridgeport ISD
             ...      
9154    Waxahachie ISD
9155       Red Oak ISD
9156    Waxahachie ISD
9157    Midlothian ISD
9158         Ennis ISD
Name: resoFacts.elementarySchoolDistrict, Length: 9159, dtype: object

In [34]:
df2['resoFacts.middleOrJuniorSchoolDistrict']

0       Bridgeport ISD
1        Northwest ISD
2             Boyd ISD
3        Northwest ISD
4       Bridgeport ISD
             ...      
9154    Waxahachie ISD
9155       Red Oak ISD
9156    Waxahachie ISD
9157    Midlothian ISD
9158         Ennis ISD
Name: resoFacts.middleOrJuniorSchoolDistrict, Length: 9159, dtype: object

In [35]:
df2[['resoFacts.homeType', 'homeType']]

resoFacts.homeType       homeType
0          SingleFamily  SINGLE_FAMILY
1          SingleFamily  SINGLE_FAMILY
2          SingleFamily  SINGLE_FAMILY
3          SingleFamily  SINGLE_FAMILY
4          SingleFamily  SINGLE_FAMILY
...                 ...            ...
9154       SingleFamily  SINGLE_FAMILY
9155       SingleFamily  SINGLE_FAMILY
9156       SingleFamily  SINGLE_FAMILY
9157       SingleFamily  SINGLE_FAMILY
9158       SingleFamily  SINGLE_FAMILY

[9159 rows x 2 columns]

In [36]:
###Fill the nan values with None
df2['resoFacts.basement'].unique()

array(['None', nan, 'Unfinished'], dtype=object)

In [37]:
df2['isListedByOwner'].unique()

array([False, nan, True], dtype=object)

In [38]:
df2['resoFacts.buyerAgencyCompensationType']

0       %
1       %
2       %
3       %
4       %
       ..
9154    %
9155    %
9156    %
9157    %
9158    %
Name: resoFacts.buyerAgencyCompensationType, Length: 9159, dtype: object

In [39]:
df2['resoFacts.buyerAgencyCompensation']

0          3
1          3
2          3
3         3%
4          3
        ... 
9154     2.5
9155       3
9156       3
9157       3
9158    3.00
Name: resoFacts.buyerAgencyCompensation, Length: 9159, dtype: object

In [40]:
df2['resoFacts.parkingFeatures'].unique()

array(["['Circular Driveway']", "['Converted Garage']",
       "['Garage Faces Front']", ...,
       "['2-Car Single Doors', 'Covered', 'Garage Door Opener', 'Garage Faces Side', 'Oversized']",
       "['2-Car Double Doors', 'Carport', 'Garage Faces Rear']",
       "['2-Car Double Doors', 'Garage Door Opener', 'Garage', 'Garage Faces Side']"],
      dtype=object)

In [41]:
df2['resoFacts.listingTerms'].unique()

array(['Cash,Conventional', 'Cash', 'Cash,Conventional,FHA,VA Loan', nan,
       'Cash,VA Loan', 'Cash,Conventional,FHA,VA Assumable',
       'Cash,Conventional,Federal Land Bank,FHA,Texas Vet,USDA Loan,VA Loan',
       'Cash,Conventional,FHA,USDA Loan,VA Loan',
       'Cash,Conventional,Federal Land Bank,FHA,USDA Loan,VA Loan',
       'Cash,Conventional,Other', 'Cash,Conventional,VA Loan',
       'Cash,Conventional,FHA',
       'Cash,Conventional,FHA,Lease Back,VA Loan',
       '1031 Exchange,Cash,Conventional,FHA,Fixed,Owner Carry Second,Private Financing Available,VA Loan',
       'Cash,Conventional,FHA,Texas Vet,VA Loan',
       'Cash,Conventional,FHA,Texas Vet,USDA Loan,VA Loan',
       'Cash,Conventional,FHA,Fixed,Texas Vet,USDA Loan,VA Loan',
       'Cash,Conventional,Texas Vet,VA Loan',
       'Cash,Contact Agent,Conventional',
       'Cash,FHA,Texas Vet,USDA Loan,VA Loan', 'Conventional',
       'Cash,Conventional,USDA Loan,VA Loan,Other',
       'Cash,Contract,Conventional,Te

In [42]:
df2['cityId']

0       23820.0
1       36648.0
2        3772.0
3           NaN
4       23820.0
         ...   
9154     7797.0
9155     7797.0
9156     7797.0
9157    36121.0
9158    42291.0
Name: cityId, Length: 9159, dtype: float64

In [43]:
df2['resoFacts.fireplaceFeatures'].unique()

array([nan, "['Other']", "['Decorative', 'Family Room']", ...,
       "['Decorative', 'Gas Log', 'Master Bedroom', 'See Through']",
       "['Electric', 'Family Room', 'Wood Burning']",
       "['Master Bedroom', 'Stone', 'Wood Burning']"], dtype=object)

In [44]:
##How many levels are there in the house
df2[['resoFacts.levels', 'streetAddress']]

resoFacts.levels          streetAddress
0                 One           2104 16th St
1                 One          509 Pettit Dr
2                 One      813 E Highway 114
3                 One      105 Dodge City Ct
4                 One          1412 Hovey St
...               ...                    ...
9154              One             4218 Fm 66
9155              One    971 Bells Chapel Rd
9156              One      145 Hartsfield Dr
9157              Two  1765 N Mockingbird Ln
9158              Two         1100 Estate Dr

[9159 rows x 2 columns]

In [45]:
##Replace null values with ['None']
df2[['resoFacts.laundryFeatures', 'streetAddress']]

resoFacts.laundryFeatures          streetAddress
0                                ['Full Size W/D Area']           2104 16th St
1                                                   NaN          509 Pettit Dr
2                                                   NaN      813 E Highway 114
3     ['Electric Dryer Hookup', 'In Hall', 'Utility ...      105 Dodge City Ct
4            ['Electric Dryer Hookup', 'Washer Hookup']          1412 Hovey St
...                                                 ...                    ...
9154                                                NaN             4218 Fm 66
9155                                                NaN    971 Bells Chapel Rd
9156                                                NaN      145 Hartsfield Dr
9157                                                NaN  1765 N Mockingbird Ln
9158  ['Electric Dryer Hookup', 'Full Size W/D Area'...         1100 Estate Dr

[9159 rows x 2 columns]

In [46]:
##For roofType if a string contains multiple types, separate them
##Other columns: 'resoFacts.fencing', 'resoFacts.architecturalStyle', 'resoFacts.structureType'
df2['resoFacts.roofType'].unique()

array(['Composition', 'Shingle', 'Metal', 'Other', 'Asphalt',
       'Asphalt,Metal,Shingle', 'Composition,Shingle',
       'Composition,Other', 'Asphalt,Shingle,Other',
       'Composition,Metal,Shake', 'Asphalt,Shingle',
       'Asphalt,Composition', 'Composition,Metal', 'Metal,Shake',
       'Concrete', 'Composition,Fiber Cement', 'Tile', 'Flat,Other',
       'Asphalt,Composition,Shingle', nan, 'Slate,Tile', 'Spanish Tile',
       'Composition,Metal,Slate,Tar/Gravel,Tile', 'Concrete,Slate,Tile',
       'Composition,Shingle,Wood', 'Composition,Slate,Tile',
       'Concrete,Spanish Tile,Tile,Other', 'Metal,Other',
       'Asphalt,Fiberglass,Shingle', 'Shingle,Wood', 'Wood', 'Slate',
       'Concrete,Tile', 'Flat', 'Composition,Concrete',
       'Composition,Tile', 'Shingle,Slate,Tile,Wood', 'Slate,Tile,Other',
       'Composition,Spanish Tile', 'Fiberglass',
       'Composition,Shingle,Other', 'Asphalt,Composition,Fiberglass',
       'Built-Up', 'Composition,Shake,Wood', 'Built-Up,Com

In [47]:
##Shows how many cars can the garage contains
##So houses can have garages or carports or both
df2[['resoFacts.garageSpaces', 'resoFacts.carportSpaces']]

resoFacts.garageSpaces  resoFacts.carportSpaces
0                        NaN                      0.0
1                        0.0                      0.0
2                        4.0                      0.0
3                        2.0                      0.0
4                        NaN                      1.0
...                      ...                      ...
9154                     2.0                      0.0
9155                     2.0                      2.0
9156                     3.0                      3.0
9157                     2.0                      0.0
9158                     3.0                      0.0

[9159 rows x 2 columns]

In [48]:
df2[['bathrooms', 'resoFacts.bathrooms', 'resoFacts.bathroomsFull']]

bathrooms  resoFacts.bathrooms  resoFacts.bathroomsFull
0           1.0                  1.0                      1.0
1           1.0                  1.0                      1.0
2           2.0                  2.0                      2.0
3           2.0                  2.0                      2.0
4           2.0                  2.0                      2.0
...         ...                  ...                      ...
9154        3.0                  3.0                      3.0
9155        2.0                  2.0                      2.0
9156        2.0                  2.0                      2.0
9157        4.0                  4.0                      4.0
9158        7.0                  7.0                      5.0

[9159 rows x 3 columns]

In [49]:
df2['resoFacts.propertySubType'].unique()

array(["['Single Family Residence']", nan, "['Farm']", "['Townhouse']",
       "['Ranch']"], dtype=object)

In [50]:
df2[ 'listed_by.recent_sales']

0       0.0
1       0.0
2       0.0
3       0.0
4       NaN
       ... 
9154    0.0
9155    0.0
9156    0.0
9157    NaN
9158    0.0
Name: listed_by.recent_sales, Length: 9159, dtype: float64

In [51]:
##Replace null with ['None']
df2['resoFacts.securityFeatures'].unique()

array([nan, "['Fire Alarm']",
       "['Carbon Monoxide Detector(s)', 'Smoke Detector(s)']",
       "['Fire Alarm', 'Smoke Detector(s)']",
       "['Burglar', 'Fire Alarm', 'Smoke Detector(s)']",
       "['Smoke Detector(s)']",
       "['Fire Alarm', 'Prewired', 'Security Lights', 'Security System', 'Smoke Detector(s)']",
       "['Security System']",
       "['Burglar', 'Prewired', 'Smoke Detector(s)']",
       "['Carbon Monoxide Detector(s)', 'Fire Alarm', 'Security Service', 'Security System', 'Smoke Detector(s)']",
       "['Carbon Monoxide Detector(s)', 'Security System', 'Smoke Detector(s)']",
       "['Burglar', 'Carbon Monoxide Detector(s)', 'Fire Alarm', 'Prewired', 'Security System', 'Smoke Detector(s)']",
       "['Burglar', 'Carbon Monoxide Detector(s)', 'Fire Alarm', 'Security System', 'Smoke Detector(s)']",
       "['Prewired', 'Security System', 'Smoke Detector(s)']",
       "['Fire Alarm', 'Security System', 'Smoke Detector(s)']",
       "['Unknown']", "['Security Syste

In [52]:
df2['resoFacts.fencing'].unique()

array([nan, 'Chain Link', 'Wood', 'Back Yard,Wrought Iron',
       'Chain Link,Fenced', 'Back Yard,Chain Link,Partial',
       'Chain Link,Privacy', 'Chain Link,Wood', 'Back Yard,Chain Link',
       'None', 'Barbed Wire', 'Back Yard,Barbed Wire', 'Other',
       'Back Yard,Rock/Stone,Wood', 'Cross Fenced,Wood', 'Cross Fenced',
       'Back Yard,Wood', 'Fenced,Wire,None', 'Wire', 'Wrought Iron',
       'Barbed Wire,Pipe', 'Metal,Wood', 'Wood,Wrought Iron',
       'Wrought Iron,Wood', 'Barbed Wire,Wrought Iron', 'Fenced',
       'Back Yard,Chain Link,Cross Fenced,Fenced,Front Yard,Full,Privacy,Split Rail,Vinyl,Wood',
       'Barbed Wire,Partial', 'Barbed Wire,Cross Fenced,Pipe',
       'Cross Fenced,Fenced,Metal', 'Back Yard,Chain Link,Gate',
       'Back Yard,Chain Link,Cross Fenced,Perimeter,Pipe,Wire',
       'Back Yard', 'Barbed Wire,Other', 'Fenced,Wire',
       'Back Yard,Gate,Privacy,Wood', 'Block,Metal,Wood',
       'Back Yard,Fenced,Wood,Other',
       'Barbed Wire,Cross Fenced,

In [53]:
df2[['address.city', 'resoFacts.elementarySchool', 'schools']]

address.city resoFacts.elementarySchool  \
0      Bridgeport                 Bridgeport   
1          Newark                 Sevenhills   
2            Boyd                       Boyd   
3          Newark                 Prairievie   
4      Bridgeport                 Bridgeport   
...           ...                        ...   
9154   Waxahachie                    Dunaway   
9155   Waxahachie                    Red Oak   
9156   Waxahachie               Oliver Clift   
9157   Midlothian         Dolores McClatchey   
9158        Ennis                     Austin   

                                                schools  
0     [{'link': 'https://www.greatschools.org/school...  
1     [{'link': 'https://www.greatschools.org/school...  
2     [{'link': 'https://www.greatschools.org/school...  
3     [{'link': 'https://www.greatschools.org/school...  
4     [{'link': 'https://www.greatschools.org/school...  
...                                                 ...  
9154  [{'link': 'https://www.greatschools.org/school...  
9155  [{'link': 'https://www.greatschools.org/school...  
9156  [{'link': 'https://www.greatschools.org/school...  
9157  [{'link': 'https://www.greatschools.org/school...  
9158  [{'link': 'https://www.greatschools.org/school...  

[9159 rows x 3 columns]

In [54]:
df2['schools'][9155]

"[{'link': 'https://www.greatschools.org/school?id=05682&state=TX', 'rating': 6, 'totalCount': 1, 'distance': 0.9, 'assigned': None, 'name': 'Wooden Elementary School', 'studentsPerTeacher': 17, 'isAssigned': True, 'size': 580, 'level': 'Primary', 'grades': 'PK-5', 'type': 'Public'}, {'link': 'https://www.greatschools.org/school?id=05680&state=TX', 'rating': 7, 'totalCount': 1, 'distance': 1, 'assigned': None, 'name': 'Red Oak Middle School', 'studentsPerTeacher': 16, 'isAssigned': True, 'size': 1433, 'level': 'Middle', 'grades': '6-8', 'type': 'Public'}, {'link': 'https://www.greatschools.org/school?id=05679&state=TX', 'rating': 4, 'totalCount': 1, 'distance': 1.4, 'assigned': None, 'name': 'Red Oak High School', 'studentsPerTeacher': 15, 'isAssigned': True, 'size': 1885, 'level': 'High', 'grades': '9-12', 'type': 'Public'}]"

In [55]:
##Use CanRaise Horses instead
df2[['resoFacts.canRaiseHorses', 'resoFacts.horseYN']]

resoFacts.canRaiseHorses resoFacts.horseYN
0                        False               NaN
1                        False               NaN
2                        False               NaN
3                        False               NaN
4                        False               NaN
...                        ...               ...
9154                      True              True
9155                      True              True
9156                     False               NaN
9157                      True              True
9158                     False               NaN

[9159 rows x 2 columns]

In [56]:
df2[['resoFacts.associationFeeIncludes', 'resoFacts.hasAssociation']]

resoFacts.associationFeeIncludes resoFacts.hasAssociation
0                                              NaN                    False
1                                              NaN                    False
2                                              NaN                    False
3                              ['Management Fees']                     True
4                                              NaN                    False
...                                            ...                      ...
9154                                           NaN                    False
9155                                           NaN                    False
9156                                           NaN                    False
9157                                           NaN                    False
9158  ['Maintenance Structure', 'Management Fees']                     True

[9159 rows x 2 columns]

In [57]:
##
df2['resoFacts.associationFeeIncludes'].unique()

array([nan, "['Management Fees']",
       "['Full Use of Facilities', 'Maintenance Structure', 'Management Fees']",
       "['Maintenance Structure']", "['Maintenance Grounds']",
       "['Full Use of Facilities', 'Management Fees']",
       "['Full Use of Facilities']",
       "['Maintenance Structure', 'Management Fees']",
       "['Maintenance Grounds', 'Management Fees']",
       "['Full Use of Facilities', 'Maintenance Structure']",
       "['Maintenance Grounds', 'Maintenance Structure']", "['Internet']",
       "['Full Use of Facilities', 'Maintenance Grounds', 'Maintenance Structure']",
       "['Maintenance Grounds', 'Maintenance Structure', 'Management Fees']",
       "['Full Use of Facilities', 'Maintenance Grounds', 'Management Fees']",
       "['Full Use of Facilities', 'Maintenance Grounds', 'Maintenance Structure', 'Management Fees']",
       "['Full Use of Facilities', 'Maintenance Grounds']",
       "['Full Use of Facilities', 'Maintenance of Common Areas']",
       "[

In [58]:
##Won't use lotSizeDimensions, not many houses have that value
df2[['resoFacts.lotSizeDimensions', 'resoFacts.lotSize']].loc[~(df2['resoFacts.lotSizeDimensions'].isnull())]

resoFacts.lotSizeDimensions resoFacts.lotSize
58                         0.158        6,926 sqft
81                        40x115        4,617 sqft
82                        55x120        6,534 sqft
86                        40x115        4,617 sqft
88                      60 x 138        8,276 sqft
...                          ...               ...
9132                     130X249        0.69 Acres
9138                      70x130        9,060 sqft
9147                    377x1557       13.48 Acres
9150                     170x272           1 Acres
9152                 31.50 ACRES       31.50 Acres

[1860 rows x 2 columns]

In [59]:
df2['resoFacts.cooling'].unique()

array(["['Ceiling Fan(s)', 'Window Unit(s)']", "['Central Air']",
       "['None', 'Other']", "['Central Air', 'Electric']",
       "['Attic Fan', 'Ceiling Fan(s)', 'Central Air', 'Electric']",
       "['Ceiling Fan(s)', 'Central Air']",
       "['Electric', 'Multi Units', 'Wall Unit(s)']", "['Central']",
       "['Ceiling Fan(s)', 'Central Air', 'Electric']",
       "['Central Air', 'Gas']",
       "['Ceiling Fan(s)', 'Central Air', 'Electric', 'Heat Pump']",
       "['Ceiling Fan(s)', 'Central Air', 'Electric', 'Wall/Window Unit(s)']",
       "['Wall/Window Unit(s)']", "['Central Air', 'Window Unit(s)']",
       "['Attic Fan', 'Ceiling Fan(s)', 'Central Air']",
       "['Ceiling Fan(s)', 'Central Air', 'ENERGY STAR Qualified Equipment']",
       "['Ceiling Fan(s)']", "['Electric']",
       "['Central Air', 'Electric', 'Heat Pump', 'Zoned']",
       "['Attic Fan', 'Electric']",
       "['Central Air', 'Electric', 'ENERGY STAR Qualified Equipment']",
       "['Wall Unit(s)']", "['Centr

In [60]:
df2[['resoFacts.yearBuilt', 'yearBuilt']].isnull().sum()

resoFacts.yearBuilt    5
yearBuilt              5
dtype: int64

In [61]:
df2[['resoFacts.associationName', 'monthlyHoaFee', 'resoFacts.hoaFee']]

resoFacts.associationName  monthlyHoaFee resoFacts.hoaFee
0                                NaN            NaN              NaN
1                                NaN            NaN              NaN
2                                NaN            NaN              NaN
3     Spectrum Association Mangement           37.0   $110 quarterly
4                                NaN            NaN              NaN
...                              ...            ...              ...
9154                             NaN            NaN              NaN
9155                             NaN            NaN              NaN
9156                             NaN            NaN              NaN
9157                             NaN            NaN              NaN
9158       Sleepy Hollow Estates HOA           27.0    $325 annually

[9159 rows x 3 columns]

In [62]:
###There are too many HOA
df2['resoFacts.associationName'].unique()

array([nan, 'Spectrum Association Mangement', 'Rolling Meadows HOA', ...,
       'HOA Summit & POA Lakeridge', 'Wildwood Development group',
       'Sleepy Hollow Estates HOA'], dtype=object)

In [63]:
##Houses can have fireplaces but they don't have the number of fireplaces
df2[['resoFacts.fireplaces', 'resoFacts.hasFireplace']].loc[~(df2['resoFacts.hasFireplace'].isnull()) &
                                                            (df2['resoFacts.fireplaces'].isnull())]

resoFacts.fireplaces resoFacts.hasFireplace
9                      NaN                   True
1806                   NaN                   True
2230                   NaN                   True
2266                   NaN                   True
4211                   NaN                   True
4685                   NaN                   True
6067                   NaN                   True
6256                   NaN                  False
6329                   NaN                  False
6353                   NaN                  False
6362                   NaN                  False
6476                   NaN                  False
6570                   NaN                  False
7253                   NaN                   True
7603                   NaN                   True
7810                   NaN                   True
8813                   NaN                   True

In [64]:
##All of these rates are from 06/04/2022
df2[['mortgageRates.arm5Rate', 'propertyTaxRate']].isnull().sum()

mortgageRates.arm5Rate    5
propertyTaxRate           0
dtype: int64

In [65]:
df2[['resoFacts.hasCarport', 'resoFacts.carportSpaces']]

resoFacts.hasCarport  resoFacts.carportSpaces
0                   False                      0.0
1                   False                      0.0
2                   False                      0.0
3                   False                      0.0
4                    True                      1.0
...                   ...                      ...
9154                False                      0.0
9155                 True                      2.0
9156                 True                      3.0
9157                False                      0.0
9158                False                      0.0

[9159 rows x 2 columns]

In [66]:
df2['resoFacts.hasView'].unique()

array([False,  True])

In [67]:
##Using this feature to get other specific rooms like kitchens
##We are at this room right now
df2['resoFacts.rooms'].iloc[0]

"[{'level': None, 'dimensions': None, 'features': None, 'roomFeatures': None, 'roomArea': None, 'roomAreaSource': None, 'roomLength': '9', 'width': None, 'roomDescription': None, 'roomWidth': '8', 'roomLevel': '1', 'roomLengthWidthUnits': None, 'roomLengthWidthSource': None, 'roomDimensions': '9 x 8', 'roomAreaUnits': None, 'roomType': 'Bathroom', 'length': None, 'description': None, 'area': None}, {'level': None, 'dimensions': None, 'features': None, 'roomFeatures': ['Solid Surface/Non-Natural Type'], 'roomArea': None, 'roomAreaSource': None, 'roomLength': '8', 'width': None, 'roomDescription': None, 'roomWidth': '10', 'roomLevel': '1', 'roomLengthWidthUnits': None, 'roomLengthWidthSource': None, 'roomDimensions': '8 x 10', 'roomAreaUnits': None, 'roomType': 'Kitchen', 'length': None, 'description': None, 'area': None}, {'level': None, 'dimensions': None, 'features': None, 'roomFeatures': ['Room for Freezer'], 'roomArea': None, 'roomAreaSource': None, 'roomLength': '10', 'width': None

In [68]:
df2['resoFacts.hasHeating'].unique()

array([True, nan, False], dtype=object)

In [69]:
##We can just use the resoFacts.bathrooms
df2[['bathrooms', 'resoFacts.bathrooms', 'resoFacts.bathroomsHalf', 
                  'resoFacts.bathroomsFull']]

bathrooms  resoFacts.bathrooms  resoFacts.bathroomsHalf  \
0           1.0                  1.0                      0.0   
1           1.0                  1.0                      0.0   
2           2.0                  2.0                      0.0   
3           2.0                  2.0                      0.0   
4           2.0                  2.0                      0.0   
...         ...                  ...                      ...   
9154        3.0                  3.0                      0.0   
9155        2.0                  2.0                      0.0   
9156        2.0                  2.0                      0.0   
9157        4.0                  4.0                      0.0   
9158        7.0                  7.0                      2.0   

      resoFacts.bathroomsFull  
0                         1.0  
1                         1.0  
2                         2.0  
3                         2.0  
4                         2.0  
...                       ...  
9154                      3.0  
9155                      2.0  
9156                      2.0  
9157                      4.0  
9158                      5.0  

[9159 rows x 4 columns]

In [73]:
df2['resoFacts.windowFeatures'].unique()

array([nan, "['Window Coverings']",
       "['Bay Window(s)', 'Window Coverings']", "['Electric Shades']",
       "['Bay Window(s)']", "['Skylight(s)', 'Window Coverings']",
       "['Bay Window(s)', 'Skylight(s)', 'Window Coverings']",
       "['Plantation Shutters']",
       "['Bay Window(s)', 'Plantation Shutters', 'Window Coverings']",
       "['Skylight(s)']", "['Plantation Shutters', 'Window Coverings']",
       "['Electric Shades', 'Plantation Shutters', 'Window Coverings']",
       "['Bay Window(s)', 'Plantation Shutters']",
       "['Plantation Shutters', 'Skylight(s)', 'Window Coverings']",
       "['Bay Window(s)', 'Electric Shades', 'Window Coverings']",
       "['Electric Shades', 'Plantation Shutters']",
       "['Electric Shades', 'Window Coverings']",
       "['Bay Window(s)', 'Skylight(s)']",
       "['Plantation Shutters', 'Skylight(s)']",
       "['Bay Window(s)', 'Plantation Shutters', 'Skylight(s)', 'Window Coverings']",
       "['Bay Window(s)', 'Electric Shades',

In [79]:
df2['resoFacts.isNewConstruction'].value_counts()

False    6758
True     2379
Name: resoFacts.isNewConstruction, dtype: int64

In [81]:
df2['solarPotential.buildFactor'].isnull().sum()

3820

In [83]:
##slate and cedar tiles for roofing can have a bad impact on solar potential score
df2['resoFacts.architecturalStyle'].unique()

array(['Traditional', nan, 'Other', 'Barndominium,Traditional', 'A-Frame',
       'Ranch', 'Barndominium', 'Ranch,Split Level,Traditional',
       'Prairie', 'Mediterranean',
       'Craftsman,Modern Farmhouse,Traditional', 'Contemporary/Modern',
       'Modern Farmhouse', 'Modern Farmhouse,Traditional', 'Craftsman',
       'Ranch,Traditional', 'Geo/Dome',
       'Contemporary/Modern,Modern Farmhouse', 'A-Frame,Other',
       'Colonial', 'Contemporary/Modern,French,Traditional',
       'Mid-Century Modern,Traditional',
       'Contemporary/Modern,Traditional', 'Craftsman,Traditional',
       'Traditional,Other', 'Split Level,Traditional', 'Tudor',
       'French,Traditional', 'Southwestern,Traditional', 'English',
       'English,Other', 'Contemporary/Modern,Ranch',
       'Contemporary/Modern,Mediterranean', 'English,Traditional',
       'Craftsman,French,Modern Farmhouse,Traditional,Tudor',
       'Contemporary/Modern,Mid-Century Modern', 'Craftsman,French,Other',
       'French,Othe

In [86]:
##Spaces outside the home that are covered by roofs, etc.
df2['resoFacts.coveredSpaces']

0       0.0
1       0.0
2       4.0
3       2.0
4       1.0
       ... 
9154    2.0
9155    4.0
9156    6.0
9157    2.0
9158    3.0
Name: resoFacts.coveredSpaces, Length: 9159, dtype: float64

In [87]:
df2['resoFacts.heating']

0                                    ['Space Heater']
1                                         ['Central']
2                                   ['None', 'Other']
3                             ['Central', 'Electric']
4                          ['Central', 'Natural Gas']
                            ...                      
9154    ['Fireplace(s)', 'Heat Pump', 'Wall Furnace']
9155                                     ['Electric']
9156                          ['Central', 'Electric']
9157                          ['Central', 'Electric']
9158                          ['Central', 'Electric']
Name: resoFacts.heating, Length: 9159, dtype: object

In [97]:
##The dropuseless columns function miss out solarFactor
df[['solarPotential.sunScore', 'solarPotential.buildFactor',
     'solarPotential.climateFactor', 'solarPotential.electricityFactor', 'solarPotential.solarFactor']]

solarPotential.sunScore  solarPotential.buildFactor  \
0                       69.13                        54.4   
1                       77.09                        62.4   
2                         NaN                         NaN   
3                         NaN                         NaN   
4                       81.93                        67.2   
...                       ...                         ...   
9154                    94.64                        80.0   
9155                    67.43                        52.8   
9156                      NaN                         NaN   
9157                      NaN                         NaN   
9158                    94.62                        80.0   

      solarPotential.climateFactor  solarPotential.electricityFactor  \
0                             6.77                               4.0   
1                             6.73                               4.0   
2                              NaN                               NaN   
3                              NaN                               NaN   
4                             6.77                               4.0   
...                            ...                               ...   
9154                          6.68                               4.0   
9155                          6.67                               4.0   
9156                           NaN                               NaN   
9157                           NaN                               NaN   
9158                          6.66                               4.0   

      solarPotential.solarFactor  
0                           3.96  
1                           3.96  
2                            NaN  
3                            NaN  
4                           3.96  
...                          ...  
9154                        3.96  
9155                        3.96  
9156                         NaN  
9157                         NaN  
9158                        3.96  

[9159 rows x 5 columns]

In [95]:
54.4 + 6.77 + 4 + 3.96

69.13

In [99]:
##If we want to look at homes in a group, we can just use their zipcode, city, state
df2['nearbyHomes'].iloc[0]

"[{'miniCardPhotos': [{'url': 'https://maps.googleapis.com/maps/api/streetview?location=1517+Lawdwin+Ave%2C+Bridgeport%2C+TX+76426&size=316x234&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=PN1qRQmZmtGZlCfr0ITXvfL_G58='}], 'zpid': 78934997, 'longitude': -97.75122, 'address': {'city': 'Bridgeport', 'state': 'TX', 'streetAddress': '1517 Lawdwin Ave', 'zipcode': '76426'}, 'price': 215700, 'homeType': 'SINGLE_FAMILY', 'homeStatus': 'OTHER', 'currency': 'USD', 'latitude': 33.218826}, {'miniCardPhotos': [{'url': 'https://photos.zillowstatic.com/fp/23d853ab2970f427aa56982d95fa6b92-p_c.jpg'}], 'zpid': 78934993, 'longitude': -97.75145, 'address': {'city': 'Bridgeport', 'state': 'TX', 'streetAddress': '1513 Lawdwin Ave', 'zipcode': '76426'}, 'price': 0, 'homeType': 'SINGLE_FAMILY', 'homeStatus': 'RECENTLY_SOLD', 'currency': 'USD', 'latitude': 33.218887}, {'miniCardPhotos': [{'url': 'https://maps.googleapis.com/maps/api/streetview?location=1510+Lawdwin+Ave%2C+Bridgeport%2C

In [114]:
##How many likes the house received
df2[['homeStatus', 'price', 'streetAddress']].loc[df2['homeStatus'] == 'RECENTLY_SOLD']

homeStatus  price    streetAddress
3945  RECENTLY_SOLD      0  9457 Lechner Rd

In [113]:
df_temp = pd.read_csv('cleaned_for_sales_houses_counties.csv')
df_temp.iloc[3945]

propertyType                                           SINGLE_FAMILY
lotArea                                                       6969.6
address                        9457 Lechner Rd, Fort Worth, TX 76179
price                                                         355000
zpid                                                        28920296
livingArea                                                    2256.0
bathrooms                                                        2.0
bedrooms                                                         3.0
country                                                          USA
currency                                                         USD
hasImage                                                        True
listingSubType.is_newHome                                      False
listingSubType.is_FSBA                                          True
listingSubType.is_openHouse                                    False
Name: 3945, dtype: object

In [116]:
df2['countyFIPS'].unique()

array([48497.,    nan, 48121., 48439., 48085., 48367., 48113., 48397.,
       48231., 48257., 48213., 48251., 48139.])

In [117]:
df2['countyId'].unique()

array([ 333,  988,  951, 1308, 2049,  978, 2516, 1833, 1827,  498])

In [118]:
df2['resoFacts.sewer'].unique()

array(["['City Sewer']", "['Aerobic Septic', 'Septic']", "['Septic']",
       nan, "['Aerobic Septic']", "['Private Sewer']",
       "['Private Sewer', 'Septic']", "['Aerobic Septic', 'MUD Sewer']",
       "['MUD Sewer']", "['Aerobic Septic', 'Private Sewer', 'Septic']",
       "['Aerobic Septic', 'Private Sewer']",
       "['City Sewer', 'MUD Sewer']",
       "['Aerobic Septic', 'City Sewer', 'Septic']",
       "['City Sewer', 'Septic']", "['Septic', 'None']",
       "['Aerobic Septic', 'City Sewer']", "['None']",
       "['City Sewer', 'Sewer Tap Fee Paid']",
       "['Aerobic Septic', 'None']", "['None', 'Septic']",
       "['Public Sewer']", "['City Sewer', 'Private Sewer']",
       "['City Sewer', 'Private Sewer', 'Septic']",
       "['City Sewer', 'None']", "['None', 'Aerobic Septic']",
       "['None', 'Septic Tank']"], dtype=object)

In [129]:
df2[['resoFacts.livingArea', 'livingArea', 'livingAreaValue', 'resoFacts.pricePerSquareFoot']]

resoFacts.livingArea  livingArea  livingAreaValue  \
0              1,072 sqft      1072.0           1072.0   
1              1,316 sqft      1316.0           1316.0   
2              2,849 sqft      2849.0           2849.0   
3              1,330 sqft      1330.0           1330.0   
4              1,492 sqft      1492.0           1492.0   
...                   ...         ...              ...   
9154           2,826 sqft      2826.0           2826.0   
9155           3,360 sqft      3360.0           3360.0   
9156           1,680 sqft      1680.0           1680.0   
9157           3,640 sqft      3640.0           3640.0   
9158           5,165 sqft      5165.0           5165.0   

      resoFacts.pricePerSquareFoot  
0                            135.0  
1                            120.0  
2                             70.0  
3                            222.0  
4                            141.0  
...                            ...  
9154                         478.0  
9155                         356.0  
9156                         744.0  
9157                         548.0  
9158                         179.0  

[9159 rows x 4 columns]

In [121]:
df2['resoFacts.structureType'].unique()

array(['Single Detached',
       'Manufactured (certificate exch),Mobile Doublewide w/Land,Single Detached',
       'Mobile Doublewide w/Land', nan,
       'Lake House,Single Detached,Vacation Home',
       'Mobile Singlewide w/Land',
       'Mobile Singlewide w/Land,Single Detached', 'Lake House',
       'Farm/Ranch House,Single Detached', 'Farm/Ranch House',
       'Attached or 1/2 Duplex', 'Manufactured (certificate exch)',
       'Manufactured (certificate exch),Mobile Doublewide w/Land',
       'Lake House,Vacation Home', 'Resort Property,Single Detached',
       'Lake House,Resort Property,Single Detached,Vacation Home',
       'Log Cabin',
       'Farm/Ranch House,Mobile Doublewide w/Land,Single Detached',
       'Garden/Zero Lot Line,Single Detached',
       'Lake House,Single Detached', 'Garden/Zero Lot Line',
       'Farm/Ranch House,Mobile Doublewide w/Land,Resort Property,Vacation Home',
       'Apartment,Farm/Ranch House,Single Detached',
       'Apartment,Mobile Doublewid

In [128]:
##Parking: The total number of cars can be parked at a house (garage spaces and carport spaces)
df2[['resoFacts.parking', 'resoFacts.garageSpaces', 'resoFacts.carportSpaces', 'streetAddress']]

resoFacts.parking  resoFacts.garageSpaces  resoFacts.carportSpaces  \
0                     0                     NaN                      0.0   
1                     0                     0.0                      0.0   
2                     4                     4.0                      0.0   
3                     2                     2.0                      0.0   
4                     1                     NaN                      1.0   
...                 ...                     ...                      ...   
9154                  2                     2.0                      0.0   
9155                  4                     2.0                      2.0   
9156                  6                     3.0                      3.0   
9157                  2                     2.0                      0.0   
9158                  3                     3.0                      0.0   

              streetAddress  
0              2104 16th St  
1             509 Pettit Dr  
2         813 E Highway 114  
3         105 Dodge City Ct  
4             1412 Hovey St  
...                     ...  
9154             4218 Fm 66  
9155    971 Bells Chapel Rd  
9156      145 Hartsfield Dr  
9157  1765 N Mockingbird Ln  
9158         1100 Estate Dr  

[9159 rows x 4 columns]

In [133]:
df2['resoFacts.lotFeatures'].unique()

array(["['Level', 'Many Trees']", nan,
       "['Corner Lot', 'Cul-De-Sac', 'Lrg. Backyard Grass']", ...,
       "['Acreage', 'Irregular Lot', 'Lrg. Backyard Grass', 'Many Trees', 'Tank/ Pond']",
       "['Acreage', 'Cedar', 'Cleared', 'Hilly', 'Lrg. Backyard Grass', 'Many Trees', 'Pasture', 'Rolling Slope', 'Sloped', 'Tank/ Pond', 'Varied']",
       "['Agricultural', 'Few Trees', 'Interior Lot', 'Landscaped', 'Lrg. Backyard Grass', 'Sprinkler System', 'Subdivided']"],
      dtype=object)

In [136]:
df2[['mortgageRates.fifteenYearFixedRate', 'mortgageRates.thirtyYearFixedRate']].isnull().sum()

mortgageRates.fifteenYearFixedRate    5
mortgageRates.thirtyYearFixedRate     5
dtype: int64

In [137]:
df2[['address.streetAddress', 'streetAddress']]

address.streetAddress          streetAddress
0              2104 16th St           2104 16th St
1             509 Pettit Dr          509 Pettit Dr
2         813 E Highway 114      813 E Highway 114
3         105 Dodge City Ct      105 Dodge City Ct
4             1412 Hovey St          1412 Hovey St
...                     ...                    ...
9154             4218 Fm 66             4218 Fm 66
9155    971 Bells Chapel Rd    971 Bells Chapel Rd
9156      145 Hartsfield Dr      145 Hartsfield Dr
9157  1765 N Mockingbird Ln  1765 N Mockingbird Ln
9158         1100 Estate Dr         1100 Estate Dr

[9159 rows x 2 columns]

In [141]:
df2['resoFacts.poolFeatures'].unique()

array([nan, "['Above Ground']", "['Gunite']",
       "['Fenced', 'Gunite', 'Heated', 'In Ground', 'Pool Sweep', 'Separate Spa/Hot Tub', 'Water Feature', 'Waterfall']",
       "['Gunite', 'Heated', 'In Ground', 'Outdoor Pool', 'Pool Sweep', 'Private', 'Pump']",
       "['Gunite', 'In Ground', 'Outdoor Pool', 'Pump']",
       "['In Ground', 'Water Feature']",
       "['Gunite', 'In Ground', 'Outdoor Pool', 'Salt Water', 'Waterfall']",
       "['In Ground', 'Outdoor Pool', 'Private', 'Separate Spa/Hot Tub', 'Water Feature', 'Waterfall']",
       "['Gunite', 'Waterfall']",
       "['Gunite', 'In Ground', 'Outdoor Pool', 'Pool Sweep', 'Water Feature', 'Waterfall']",
       "['Gunite', 'Heated', 'In Ground', 'Outdoor Pool', 'Pool/Spa Combo', 'Water Feature']",
       "['Gunite', 'In Ground', 'Outdoor Pool', 'Pool/Spa Combo', 'Pump', 'Waterfall']",
       "['Gunite', 'Heated', 'In Ground', 'Outdoor Pool', 'Pool Sweep', 'Pool/Spa Combo', 'Pump', 'Water Feature', 'Waterfall', 'Other']",
       

In [3]:
#Done with raw features 
chosen_columns = ['zpid', 'isListedByOwner', 'resoFacts.yearBuilt', 'resoFacts.hasAssociation', 'resoFacts.associationFeeIncludes', 
                  'annualHomeownersInsurance', 'monthlyHoaFee', 'resoFacts.hoaFee', 'resoFacts.patioAndPorchFeatures', 
                  'resoFacts.lotFeatures', 'resoFacts.sewer', 'resoFacts.waterSource', 'schools',
                  'resoFacts.elementarySchool', 'resoFacts.elementarySchoolDistrict', 'resoFacts.middleOrJuniorSchool', 
                  'resoFacts.highSchool', 'resoFacts.highSchoolDistrict', 'resoFacts.middleOrJuniorSchoolDistrict', 
                  'resoFacts.pricePerSquareFoot', 'livingAreaValue', 'resoFacts.exteriorFeatures', 'resoFacts.hasPrivatePool',
                  'resoFacts.poolFeatures', 
                  'resoFacts.propertySubType', 'resoFacts.interiorFeatures', 'solarPotential.sunScore', 'solarPotential.buildFactor',
                  'solarPotential.climateFactor', 'solarPotential.electricityFactor', 'solarPotential.solarFactor', 
                  'resoFacts.hasCooling', 'resoFacts.cooling', 'resoFacts.hasHeating', 'resoFacts.heating', 
                  'resoFacts.structureType', 'resoFacts.windowFeatures', 'resoFacts.architecturalStyle', 'resoFacts.vegetation', 
                  'resoFacts.fencing', 'resoFacts.greenEnergyEfficient', 'resoFacts.taxAnnualAmount', 'resoFacts.foundationDetails', 
                  'resoFacts.canRaiseHorses', 'resoFacts.utilities', 'resoFacts.hasGarage', 'resoFacts.hasAttachedGarage', 
                  'resoFacts.hasCarport', 'resoFacts.carportSpaces', 'resoFacts.parkingFeatures', 'resoFacts.garageSpaces', 
                  'resoFacts.parking',
                  'resoFacts.hasSpa', 'resoFacts.hasView', 'resoFacts.homeType', 'resoFacts.rooms', 'resoFacts.coveredSpaces', 
                  'resoFacts.constructionMaterials', 'resoFacts.appliances', 'resoFacts.flooring', 'resoFacts.basement', 'bedrooms',
                  'resoFacts.communityFeatures', 'resoFacts.bathrooms', 'resoFacts.bathroomsHalf', 'resoFacts.bathroomsFull', 
                  'resoFacts.hasLandLease', 'resoFacts.hasFireplace', 'resoFacts.fireplaces', 'resoFacts.fireplaceFeatures', 
                  'resoFacts.levels', 'resoFacts.securityFeatures', 'resoFacts.roofType', 'streetAddress', 'longitude', 'latitude', 
                  'zipcode', 'countyId', 'city', 'resoFacts.buyerAgencyCompensation', 'resoFacts.buyerAgencyCompensationType', 
                  'favoriteCount', 'resoFacts.isNewConstruction', 'mortgageRates.fifteenYearFixedRate', 
                  'mortgageRates.thirtyYearFixedRate', 'mortgageRates.arm5Rate', 'propertyTaxRate', 'price']

time_columns = ['resoFacts.onMarketDate', 'resoFacts.daysOnZillow', 'mortgageRates.fifteenYearFixedRate', 
                'mortgageRates.thirtyYearFixedRate', 'taxHistory']

In [143]:
list(set(df.columns.tolist()) - set(chosen_columns))

['listingProvider.showLogos',
 'resoFacts.livingArea',
 'resoFacts.view',
 'resoFacts.onMarketDate',
 'resoFacts.elevationUnits',
 'resoFacts.numberOfUnitsInCommunity',
 'address.state',
 'building',
 'resoFacts.marketingType',
 'providerListingID',
 'resoFacts.landLeaseAmount',
 'timeOnZillow',
 'resoFacts.woodedArea',
 'resoFacts.propertyCondition',
 'resoFacts.stories',
 'resoFacts.parcelNumber',
 'resoFacts.irrigationWaterRightsYN',
 'listingProvider.disclaimerText',
 'datePosted',
 'listed_by.zpro',
 'resoFacts.bathroomsOneQuarter',
 'listingProvider.logos',
 'resoFacts.waterfrontFeatures',
 'resoFacts.greenWaterConservation',
 'resoFacts.isSeniorCommunity',
 'resoFacts.bodyType',
 'zestimateHighPercent',
 'listingProvider.agentName',
 'contingentListingType',
 'resoFacts.mainLevelBedrooms',
 'resoFacts.frontageLength',
 'resoFacts.availabilityDate',
 'resoFacts.leaseTerm',
 'resoFacts.irrigationWaterRightsAcres',
 'listed_by.rating_average',
 'resoFacts.waterView',
 'resoFacts.op

In [4]:
len(chosen_columns)

88

# Cleaning the dataframe with the chosen columns

In [5]:
df2 = df.copy()[chosen_columns]

In [8]:
##Remember we have a list of counties run through a loop 
##The order of that list can determine the number that represents the counties
##'wise county, tx', 'denton county, tx', 'collin county, tx', 'parker county, tx', 'tarrant county, tx', 
##'dallas county, tx', 'rockwall county, tx', 'kaufman county, tx', 'johnson county, tx', 'ellis county, tx'
##Follow the order of the county above, these numbers represents these counties respectively.
df2['countyId'].unique()

array([ 333,  988,  951, 1308, 2049,  978, 2516, 1833, 1827,  498],
      dtype=int64)

In [ ]:
##nan here is actually a float number
##Replaces null values with ['None'] or sth
##Create columns based on lists within a row's variable
##Columns that have this: 'resoFacts.patioAndPorchFeatures', 'resoFacts.waterSource', 'resoFacts.exteriorFeatures'
##'resoFacts.vegetation', 'resoFacts.greenEnergyEfficient', 'resoFacts.foundationDetails', 'resoFacts.utilities'
##'resoFacts.appliances', 'resoFacts.flooring', 'resoFacts.parkingFeatures', 'resoFacts.fireplaceFeatures'
##'resoFacts.laundryFeatures', 'resoFacts.propertySubType', 'resoFacts.laundryFeatures', 'resoFacts.securityFeatures',
##'schools', 'resoFacts.associationFeeIncludes', 'resoFacts.cooling', 'resoFacts.fireplaces', 'resoFacts.windowFeatures'
##'resoFacts.heating', 'resoFacts.sewer', 'resoFacts.poolFeatures' 

##utilities that is null can be seen as electricity
##For green energy, we can create a column where if it has green energy or not

##Fill null sun score values with mean or median of sun scores in the zip code area
##resoFacts.hasAssociation is if the house has HOA or not
##resoFacts.taxAnnualAmount: The annual amount is currently this year
##resoFacts.basement: Fill the nan values with None
##resoFacts.buyerAgencyCompensation: Only numbers should be there, nopercent signs
##resoFacts.levels: How many levels are there in the house
##For roofType if a string contains multiple types, separate them
##Other columns: 'resoFacts.fencing', 'resoFacts.architecturalStyle', 'resoFacts.structureType'
##Houses can have fireplaces but they don't have the number of fireplaces
##All of these rates (mortgage rates, property tax rate) are from 06/04/2022
##resoFacts.rooms: Using this feature to get other specific rooms like kitchens
##slate and cedar tiles for roofing can have a bad impact on solar potential score
##resoFacts.coveredSpaces: Spaces outside the home that are covered by roofs, etc.
##resoFacts.parking: The total number of cars can be parked at a house (resoFacts.garageSpaces and resoFacts.carportSpaces)

In [7]:
df2.isnull().sum()

zpid                                     0
isListedByOwner                          1
resoFacts.yearBuilt                      5
resoFacts.hasAssociation                17
resoFacts.associationFeeIncludes      4269
                                      ... 
mortgageRates.fifteenYearFixedRate       5
mortgageRates.thirtyYearFixedRate        5
mortgageRates.arm5Rate                   5
propertyTaxRate                          0
price                                    0
Length: 88, dtype: int64

#### Read in the  cleaned_for_sales_houses_counties.csv and join the 2 dataframes above

In [28]:
##Let's look at the basic columns first
#basic_columns = 

livingArea   price    streetAddress
5961        12.0  255000  Trail Ln #11224